name: gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  API_BASE: ${{ secrets.ENV_API_BASE }}
  PLATFORM: gh-pages

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: recursive
        #   fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: gh.d3bu.net
