name: gh-pages

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  API_BASE: ${{ secrets.ENV_API_BASE }}
  PLATFORM: gh-pages
  CNAME: gh.d3bu.net

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   submodules: recursive
        #   fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: ${{ env.CNAME }}
